apiVersion: v1
kind: Namespace
metadata:
  name: ai-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ai-services
spec:
  replicas: 1
  selector:
    matchLabels: { app: ollama }
  template:
    metadata:
      labels: { app: ollama }
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        volumeMounts:
        - mountPath: "/root/.ollama/"
          name: ollama-storage
        ports:
        - containerPort: 11434 
      volumes:
      - name: ollama-storage
        hostPath:
          path: /share
          type: DirectoryOrCreate
      nodeName:
        k8s-node3
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ai-services
spec:
  type: NodePort
  selector: { app: ollama }
  ports:
  - port: 11434
    targetPort: 11434
